sources:
  - name: GrpcApi
    handler:
      grpc:
        endpoint: localhost:8081
        source: ./src/api/hello.proto
  - name: VaporApi
    handler:
      openapi:
        endpoint: localhost:8080
        source: ./hello/open.yaml

