sources:
  - name: GrpcApi
    handler:
      grpc:
        endpoint: localhost:8081
        source: ./src/api/hello.proto
        metaData:
          Authorization: 'Bearer {context.headers["token"]}'
          someStaticValue: 'MyStaticValue'
  - name: VaporApi
    handler:
      openapi:
        endpoint: http://localhost:8080
        source: ./hello/open.yaml
        operationHeaders:
          Authorization: 'Bearer {context.headers["token"]}'